---
- hosts: localhost
  connection: local
  tasks:
    - name: get file
      get_url:
        url: "http://{{item}}/index.html"
        dest: "/tmp/{{item}}"
      ignore_errors: yes
      with_items:
        - kube-poc-uworker1
        - kube-poc-uworker2
        - kube-poc-uworker3

