---
- hosts: localhost
  tasks:
    - name: download transcation_list
      block:
        - get_url:
            url: http://kube-poc-uworker2/transaction_list
            dest: /home/ansible/transaction_list
        - replace:
            path: /home/ansible/transaction_list
            regexp: "#BLANKLINE"
            replace: "\n"
        - debug: msg="File downloaded"
      rescue:
        - debug: msg="kube-proc-uworker2 appears to be down. Try agin later."
      always:
        - debug: msg="Attempt completed."

